### PR TITLE
test

### PR DESCRIPTION
**Pull request by imsodin**
Test I wrote a while ago - very limited, but better than no test :)

### CODE REVIEW

**Comment by acolomb** [comment]
Thank you for this addition.  I was going to look at the tests once the general structure is approved - just about now :-)

You had a slightly more elaborate test function [in a comment](https://github.com/syncthing/syncthing/pull/6443#issuecomment-640072688) on the original PR.  Let me see how much of that can easily be integrated here.

**Comment by acolomb** [comment]
Never mind, the linked test is basically the same, but introduces a third device.  I thought that one was actually used, but it's just a replacement for `device1`.  I think I can make use of it though.

For my local testing, I had once introduced the following in `lib/protocol/deviceid.go`:

```go
    var (
    	// ...
    	EmptyDeviceID  = DeviceID{ /* all zeroes */ }
    	TestDeviceID1  = repeatedDeviceID(0x01)
    	TestDeviceID2  = repeatedDeviceID(0x02)
    )
```

Do you think something like that could be used overall for the test cases?

**Comment by imsodin** [comment]
That basically already exists in `lib/model/testutils_test.go`. I could have used some stuff from there in tests of other packages and vice-versa, so having it in a common place would probably be useful indeed. However I'd put it in a separate package, that's only ever imported from tests, maybe `lib/testutil`.

**Comment by acolomb** [comment]
That would be a bigger change though, as many tests would be affected.  Let's keep it separate for a later PR.

**Pull request merged**
